// Generated by gencpp from file learning_synchronizer/Person.msg
// DO NOT EDIT!


#ifndef LEARNING_SYNCHRONIZER_MESSAGE_PERSON_H
#define LEARNING_SYNCHRONIZER_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace learning_synchronizer
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : header()
    , age(0)
    , height(0.0)
    , name()  {
    }
  Person_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , age(0)
    , height(0.0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _age_type;
  _age_type age;

   typedef float _height_type;
  _height_type height;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::learning_synchronizer::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_synchronizer::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::learning_synchronizer::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::learning_synchronizer::Person > PersonPtr;
typedef boost::shared_ptr< ::learning_synchronizer::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_synchronizer::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_synchronizer::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_synchronizer::Person_<ContainerAllocator1> & lhs, const ::learning_synchronizer::Person_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.age == rhs.age &&
    lhs.height == rhs.height &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_synchronizer::Person_<ContainerAllocator1> & lhs, const ::learning_synchronizer::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_synchronizer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_synchronizer::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_synchronizer::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_synchronizer::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_synchronizer::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_synchronizer::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_synchronizer::Person_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_synchronizer::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6c4bc89784cc3120ef300313a0d4bb7";
  }

  static const char* value(const ::learning_synchronizer::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6c4bc89784cc312ULL;
  static const uint64_t static_value2 = 0x0ef300313a0d4bb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_synchronizer::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_synchronizer/Person";
  }

  static const char* value(const ::learning_synchronizer::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_synchronizer::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 age\n"
"float32 height\n"
"string name\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::learning_synchronizer::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_synchronizer::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.age);
      stream.next(m.height);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_synchronizer::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_synchronizer::Person_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_SYNCHRONIZER_MESSAGE_PERSON_H
