// Generated by gencpp from file learning_service/Add.msg
// DO NOT EDIT!


#ifndef LEARNING_SERVICE_MESSAGE_ADD_H
#define LEARNING_SERVICE_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <learning_service/AddRequest.h>
#include <learning_service/AddResponse.h>


namespace learning_service
{

struct Add
{

typedef AddRequest Request;
typedef AddResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Add
} // namespace learning_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_service::Add > {
  static const char* value()
  {
    return "eb3958e9614615192c3e63bd0b5590df";
  }

  static const char* value(const ::learning_service::Add&) { return value(); }
};

template<>
struct DataType< ::learning_service::Add > {
  static const char* value()
  {
    return "learning_service/Add";
  }

  static const char* value(const ::learning_service::Add&) { return value(); }
};


// service_traits::MD5Sum< ::learning_service::AddRequest> should match
// service_traits::MD5Sum< ::learning_service::Add >
template<>
struct MD5Sum< ::learning_service::AddRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_service::Add >::value();
  }
  static const char* value(const ::learning_service::AddRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_service::AddRequest> should match
// service_traits::DataType< ::learning_service::Add >
template<>
struct DataType< ::learning_service::AddRequest>
{
  static const char* value()
  {
    return DataType< ::learning_service::Add >::value();
  }
  static const char* value(const ::learning_service::AddRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_service::AddResponse> should match
// service_traits::MD5Sum< ::learning_service::Add >
template<>
struct MD5Sum< ::learning_service::AddResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_service::Add >::value();
  }
  static const char* value(const ::learning_service::AddResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_service::AddResponse> should match
// service_traits::DataType< ::learning_service::Add >
template<>
struct DataType< ::learning_service::AddResponse>
{
  static const char* value()
  {
    return DataType< ::learning_service::Add >::value();
  }
  static const char* value(const ::learning_service::AddResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_SERVICE_MESSAGE_ADD_H
