// Generated by gencpp from file learning_service/AddResponse.msg
// DO NOT EDIT!


#ifndef LEARNING_SERVICE_MESSAGE_ADDRESPONSE_H
#define LEARNING_SERVICE_MESSAGE_ADDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_service
{
template <class ContainerAllocator>
struct AddResponse_
{
  typedef AddResponse_<ContainerAllocator> Type;

  AddResponse_()
    : sum(0.0)  {
    }
  AddResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef double _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::learning_service::AddResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_service::AddResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddResponse_

typedef ::learning_service::AddResponse_<std::allocator<void> > AddResponse;

typedef boost::shared_ptr< ::learning_service::AddResponse > AddResponsePtr;
typedef boost::shared_ptr< ::learning_service::AddResponse const> AddResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_service::AddResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_service::AddResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_service::AddResponse_<ContainerAllocator1> & lhs, const ::learning_service::AddResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_service::AddResponse_<ContainerAllocator1> & lhs, const ::learning_service::AddResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_service::AddResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_service::AddResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_service::AddResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_service::AddResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_service::AddResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_service::AddResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_service::AddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "981739b4699a7cf1b15030371beffb96";
  }

  static const char* value(const ::learning_service::AddResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x981739b4699a7cf1ULL;
  static const uint64_t static_value2 = 0xb15030371beffb96ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_service::AddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_service/AddResponse";
  }

  static const char* value(const ::learning_service::AddResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_service::AddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 sum\n"
;
  }

  static const char* value(const ::learning_service::AddResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_service::AddResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_service::AddResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_service::AddResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<double>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_SERVICE_MESSAGE_ADDRESPONSE_H
