(cl:defpackage learning_action-msg
  (:use )
  (:export
   "<COUNTACTION>"
   "COUNTACTION"
   "<COUNTACTIONFEEDBACK>"
   "COUNTACTIONFEEDBACK"
   "<COUNTACTIONGOAL>"
   "COUNTACTIONGOAL"
   "<COUNTACTIONRESULT>"
   "COUNTACTIONRESULT"
   "<COUNTFEEDBACK>"
   "COUNTFEEDBACK"
   "<COUNTGOAL>"
   "COUNTGOAL"
   "<COUNTRESULT>"
   "COUNTRESULT"
  ))

