; Auto-generated. Do not edit!


(cl:in-package learning_action-msg)


;//! \htmlinclude CountResult.msg.html

(cl:defclass <CountResult> (roslisp-msg-protocol:ros-message)
  ((finish
    :reader finish
    :initarg :finish
    :type cl:integer
    :initform 0))
)

(cl:defclass CountResult (<CountResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learning_action-msg:<CountResult> is deprecated: use learning_action-msg:CountResult instead.")))

(cl:ensure-generic-function 'finish-val :lambda-list '(m))
(cl:defmethod finish-val ((m <CountResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learning_action-msg:finish-val is deprecated.  Use learning_action-msg:finish instead.")
  (finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountResult>) ostream)
  "Serializes a message object of type '<CountResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'finish)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'finish)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'finish)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'finish)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountResult>) istream)
  "Deserializes a message object of type '<CountResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'finish)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'finish)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'finish)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'finish)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountResult>)))
  "Returns string type for a message object of type '<CountResult>"
  "learning_action/CountResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountResult)))
  "Returns string type for a message object of type 'CountResult"
  "learning_action/CountResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountResult>)))
  "Returns md5sum for a message object of type '<CountResult>"
  "9f01ccdf5249063136ea1f071c35e0bd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountResult)))
  "Returns md5sum for a message object of type 'CountResult"
  "9f01ccdf5249063136ea1f071c35e0bd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountResult>)))
  "Returns full string definition for message of type '<CountResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountResult)))
  "Returns full string definition for message of type 'CountResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CountResult
    (cl:cons ':finish (finish msg))
))
