// Generated by gencpp from file learning_action/CountResult.msg
// DO NOT EDIT!


#ifndef LEARNING_ACTION_MESSAGE_COUNTRESULT_H
#define LEARNING_ACTION_MESSAGE_COUNTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_action
{
template <class ContainerAllocator>
struct CountResult_
{
  typedef CountResult_<ContainerAllocator> Type;

  CountResult_()
    : finish(0)  {
    }
  CountResult_(const ContainerAllocator& _alloc)
    : finish(0)  {
  (void)_alloc;
    }



   typedef uint32_t _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::learning_action::CountResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_action::CountResult_<ContainerAllocator> const> ConstPtr;

}; // struct CountResult_

typedef ::learning_action::CountResult_<std::allocator<void> > CountResult;

typedef boost::shared_ptr< ::learning_action::CountResult > CountResultPtr;
typedef boost::shared_ptr< ::learning_action::CountResult const> CountResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_action::CountResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_action::CountResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_action::CountResult_<ContainerAllocator1> & lhs, const ::learning_action::CountResult_<ContainerAllocator2> & rhs)
{
  return lhs.finish == rhs.finish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_action::CountResult_<ContainerAllocator1> & lhs, const ::learning_action::CountResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_action::CountResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_action::CountResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_action::CountResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_action::CountResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_action::CountResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_action::CountResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_action::CountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f01ccdf5249063136ea1f071c35e0bd";
  }

  static const char* value(const ::learning_action::CountResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f01ccdf52490631ULL;
  static const uint64_t static_value2 = 0x36ea1f071c35e0bdULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_action::CountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_action/CountResult";
  }

  static const char* value(const ::learning_action::CountResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_action::CountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 finish\n"
;
  }

  static const char* value(const ::learning_action::CountResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_action::CountResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_action::CountResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_action::CountResult_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_ACTION_MESSAGE_COUNTRESULT_H
