// Generated by gencpp from file learning_action/CountFeedback.msg
// DO NOT EDIT!


#ifndef LEARNING_ACTION_MESSAGE_COUNTFEEDBACK_H
#define LEARNING_ACTION_MESSAGE_COUNTFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_action
{
template <class ContainerAllocator>
struct CountFeedback_
{
  typedef CountFeedback_<ContainerAllocator> Type;

  CountFeedback_()
    : percent_complete(0.0)  {
    }
  CountFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::learning_action::CountFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_action::CountFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CountFeedback_

typedef ::learning_action::CountFeedback_<std::allocator<void> > CountFeedback;

typedef boost::shared_ptr< ::learning_action::CountFeedback > CountFeedbackPtr;
typedef boost::shared_ptr< ::learning_action::CountFeedback const> CountFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_action::CountFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_action::CountFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_action::CountFeedback_<ContainerAllocator1> & lhs, const ::learning_action::CountFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_action::CountFeedback_<ContainerAllocator1> & lhs, const ::learning_action::CountFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_action::CountFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_action::CountFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_action::CountFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_action::CountFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_action::CountFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_action::CountFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_action::CountFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::learning_action::CountFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_action::CountFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_action/CountFeedback";
  }

  static const char* value(const ::learning_action::CountFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_action::CountFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percent_complete\n"
;
  }

  static const char* value(const ::learning_action::CountFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_action::CountFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_action::CountFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_action::CountFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_ACTION_MESSAGE_COUNTFEEDBACK_H
