// Generated by gencpp from file learning_action/CountGoal.msg
// DO NOT EDIT!


#ifndef LEARNING_ACTION_MESSAGE_COUNTGOAL_H
#define LEARNING_ACTION_MESSAGE_COUNTGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_action
{
template <class ContainerAllocator>
struct CountGoal_
{
  typedef CountGoal_<ContainerAllocator> Type;

  CountGoal_()
    : goal_num(0)  {
    }
  CountGoal_(const ContainerAllocator& _alloc)
    : goal_num(0)  {
  (void)_alloc;
    }



   typedef uint32_t _goal_num_type;
  _goal_num_type goal_num;





  typedef boost::shared_ptr< ::learning_action::CountGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_action::CountGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CountGoal_

typedef ::learning_action::CountGoal_<std::allocator<void> > CountGoal;

typedef boost::shared_ptr< ::learning_action::CountGoal > CountGoalPtr;
typedef boost::shared_ptr< ::learning_action::CountGoal const> CountGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_action::CountGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_action::CountGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_action::CountGoal_<ContainerAllocator1> & lhs, const ::learning_action::CountGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal_num == rhs.goal_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_action::CountGoal_<ContainerAllocator1> & lhs, const ::learning_action::CountGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_action::CountGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_action::CountGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_action::CountGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_action::CountGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_action::CountGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_action::CountGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_action::CountGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "255f71eb93c304464e7bb2f6b7689d25";
  }

  static const char* value(const ::learning_action::CountGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x255f71eb93c30446ULL;
  static const uint64_t static_value2 = 0x4e7bb2f6b7689d25ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_action::CountGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_action/CountGoal";
  }

  static const char* value(const ::learning_action::CountGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_action::CountGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"uint32 goal_num\n"
;
  }

  static const char* value(const ::learning_action::CountGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_action::CountGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_action::CountGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_action::CountGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.goal_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_ACTION_MESSAGE_COUNTGOAL_H
